<?php

/**
 * Implements hook_search_api_processor_info().
 */
function search_api_taxonomy_search_api_processor_info() {
  $processors['search_api_taxonomy_hierarchy'] = array(
    'name' => t('Taxonomy Hierarchy'),
    'description' => t('This processor indexes the parents of taxonomy terms.'),
    'class' => 'SearchApiTaxonomyHierarchyProcessor',
    'weight' => 30,
  );

  return $processors;
}

/**
 * Implements hook_facetapi_widgets().
 */
function search_api_taxonomy_facetapi_widgets() {
  return array(
    'searchapitaxonomy_checkbox_links_top_level' => array(
      'handler' => array(
        'label' => t('Links with checkboxes - Top level only'),
        'class' => 'SearchAPITaxonomyFacetapiWidgetCheckboxLinksTopLevel',
        'query types' => array('term'),
      ),
    ),
  );
}
